### ISSUE TITLE
[资料分享] Programming Kubernetes 中文版

### ISSUE THREAD

**Issue by rootsongjc** [cloudnativeto/sig-k8s-source-code#12]
《Programming Kubernetes》本书即将引进国内出版，敬请关注。

**Comment by liushaoxiong10** [comment]
申请阅读 @Miss-you  Github： liushaoxiong10

**Comment by arthaslll** [comment]
申请阅读 @Miss-you Github：arthaslll

**Comment by FANHIDE** [comment]
申请阅读 @Miss-you GitHub：FANHIDE

**Comment by YouEclipse** [comment]
申请阅读 @Miss-you Github: YouEclipse

**Comment by liuyangc3** [comment]
申请阅读 @Miss-you GitHub: liuyangc3

**Comment by JaneLiuL** [comment]
申请阅读 @Miss-you  GitHub: JaneLiuL

**Comment by ruster-cn** [comment]
申请阅读 @Miss-you  GitHub: ruster-cn

**Comment by derik93** [comment]
申请阅读 @Miss-you GitHub: derik93

**Comment by linyongluis** [comment]
申请阅读 @Miss-you GitHub: linyongluis

**Comment by windyear** [comment]
申请阅读@Miss-you Github:@windyear

**Comment by smurf28** [comment]
申请阅读@Miss-you

**Comment by sundongmin** [comment]
申请阅读@Miss-you Github: @sundongmin

**Comment by smurf28** [comment]
申请阅读@Miss-you Github: @smurf28

**Comment by huizluo** [comment]
申请阅读@Miss-you Github: @huizluo

**Comment by callmevincent** [comment]
申请阅读@Miss-you Github:  **callmevincent**

**Comment by zhangguanzhang** [comment]
申请阅读@Miss-you Github: zhangguanzhang

**Comment by linxuyalun** [comment]
申请阅读@Miss-you Github: linxuyalun

**Comment by yingsunjiu** [comment]
@Miss-you GitHub: yingsunjiu

**Comment by Mr-Linus** [comment]
申请阅读 @Miss-you GitHub：Mr-Linus

**Comment by tanjunchen** [comment]
申请阅读 @Miss-you GitHub：tanjunchen 
thanks

**Comment by Sakuralbj** [comment]
申请阅读@Miss-you Github: Sakuralbj 
thanks!

**Comment by kqzh** [comment]
申请阅读 @Miss-you GitHub：kqzh
thanks

**Comment by Viyond** [comment]
申请阅读 @Miss-you GitHub：Viyond
thanks

**Comment by LeoWenxiang** [comment]
申请阅读 @Miss-you GitHub：LeoWenxiang
thanks

**Comment by xichengliudui** [comment]
申请阅读 @Miss-you GitHub：xichengliudui
thanks

**Comment by withlin** [comment]
申请阅读 @Miss-you GitHub：withlin
thanks

**Comment by cobb-tx** [comment]
申请阅读 @Miss-you GitHub：cobb-tx
thanks

**Comment by xiaofeitu2** [comment]
申请阅读 @Miss-you GitHub：xiaofeitu2
thanks

**Comment by mingqing** [comment]
申请阅读 @Miss-you GitHub：mingqing
thanks

**Comment by PudongLi** [comment]
申请阅 @Miss-you Github: pudongli

**Comment by loveresolution** [comment]
申请阅读 @Miss-you GitHub：yangguoandresolution
thanks

**Comment by gyohuangxin** [comment]
申请阅读@Miss-you Github: gyohuangxin

**Comment by nevermosby** [comment]
申请阅读 @Miss-you , github id: nevermosby

**Comment by felix0080** [comment]
申请阅读 @Miss-you ,github id: felix0080

**Comment by lyzhang1999** [comment]
申请阅读 @Miss-you GitHub： @lyzhang1999

**Comment by rainingmaster** [comment]
申请阅读 @Miss-you Github: rainingmaster。感谢！

**Comment by abhty822** [comment]
申请阅读 @Miss-you Github: Jabhty822

**Comment by zackzhangkai** [comment]
申请阅读 @Miss-you  Github: zackzhangkai

**Comment by champly** [comment]
申请阅读 @Miss-you Github: champly

**Comment by akaxb** [comment]
申请阅读 @Miss-you  Github: akaxb

**Comment by wwq-2020** [comment]
申请阅读 @Miss-you  GitHub：wwq-2020

**Comment by Nightbone** [comment]
申请阅读 @Miss-you GitHub：Nightbone

**Comment by weiyouwozuiku** [comment]
申请阅读 @Miss-you Github: weiyouwozuiku

**Comment by xibuka** [comment]
申请阅读 @Miss-you GitHub：xibuka

**Comment by janexiaobai** [comment]
申请阅读 谢谢 @Miss-you

**Comment by ycliu912** [comment]
申请阅读 @Miss-you Github: ycliu912

**Comment by ghostloda** [comment]
申请阅读 @Miss-you Github: ghostloda

**Comment by skymyyang** [comment]
申请阅读 @Miss-you Github: skymyyang

**Comment by WangShuXian6** [comment]
申请阅读 @Miss-you Github: wangshuxian6

**Comment by cuisongliu** [comment]
申请阅读 @Miss-you Github: cuisongliu

**Comment by chengyh2golang** [comment]
申请阅读 @Miss-you Github: chengyh2golang

**Comment by GolemHerry** [comment]
申请阅读 @Miss-you Github: GolemHerry

**Comment by qxhy123** [comment]
申请阅读 @Miss-you Github: qxhy123

**Comment by StephenLiuYa** [comment]
申请阅读 @Miss-you Github: StephenLiuYa

**Comment by idevz** [comment]
申请阅读 @Miss-you GitHub: idevz

**Comment by zbyufei** [comment]
申请阅读 @Miss-you Github: zbyufei

**Comment by Lvzhenqian** [comment]
申请阅读 @Miss-you  Github: lvzhenqian

**Comment by cailili19931106** [comment]
申请阅读 @Miss-you  Github: cll1010905536

**Comment by long904** [comment]
申请阅读 @Miss-you Github: long904

**Comment by leonard520** [comment]
申请阅读 @Miss-you Github: leonard520

**Comment by burxtx** [comment]
申请阅读 @Miss-you Github: burxtx

**Comment by hyschumi** [comment]
申请阅读 @Miss-you Github: hyschumi

**Comment by Howie66** [comment]
申请阅读 @Miss-you Github:Howie66

**Comment by CrazyHZM** [comment]
申请阅读 @Miss-you Github: CrazyHZM

**Comment by lxyqwer** [comment]
申请阅读 @Miss-you Github:lxyqwer

**Comment by ghl1024** [comment]
申请阅读 @Miss-you GitHub：ghl1024

**Comment by khalke** [comment]
申请阅读 @Miss-you  GitHub: khalke

**Comment by QQ-ing** [comment]
申请阅读 @Miss-you Github: QQ-ing

**Comment by ddy4633** [comment]
申请阅读 @Miss-you Github: ddy4633

**Comment by wmy-one** [comment]
申请阅读 @Miss-you Github: wmy-one

**Comment by jxlwqq** [comment]
申请阅读 @Miss-you GitHub：jxlwqq

**Comment by zou2699** [comment]
申请阅读 @Miss-you GitHub：zou2699

**Comment by cyancow** [comment]
申请阅读 @Miss-you GitHub: cyancow

**Comment by JadeQin** [comment]
申请阅读 @Miss-you GitHub: JadeQin

**Comment by missing-cn** [comment]
@Miss-you 申请阅读，非常感谢！

**Comment by sawyerwu** [comment]
申请阅读 @Miss-you GitHub：sawyerwu

**Comment by haiker2011** [comment]
申请阅读 @Miss-you GitHub：haiker2011

**Comment by liyebing** [comment]
申请阅读 @Miss-you GitHub：liyebing

**Comment by kenwoodjw** [comment]
申请阅读 @Miss-you GitHub：kenwoodjw

**Comment by kenwoodjw** [comment]
申请阅读 @Miss-you GitHub：kenwoodjw

**Comment by kenwoodjw** [comment]
申请阅读 @Miss-you GitHub：kenwoodjw

**Comment by kenwoodjw** [comment]
申请阅读 @Miss-you GitHub：kenwoodjw

**Comment by CharlesZHENG** [comment]
申请阅读 @Miss-you   GitHub：CharlesZHENG

**Comment by aaronsh01** [comment]
申请阅读 @Miss-you GitHub：aaronsh01

**Comment by BigbigY** [comment]
申请阅读 @Miss-you  Github: BigbigY

**Comment by rice5** [comment]
申请阅读 @Miss-you Github: rice5

**Comment by wwangbinbin** [comment]
申请阅读 @Miss-you Github: wwangbinbin

**Comment by security00** [comment]
申请阅读 @Miss-you Github: security00

**Comment by judexzhu** [comment]
申请阅读 @Miss-you Github: judexzhu

**Comment by Frank-liang** [comment]
申请阅读 @Miss-you Github: Frank-liang

**Comment by Liaoyingjie** [comment]
申请阅读 @Miss-you Github: liaoyingjie

**Comment by xiaoxiaoling** [comment]
申请阅读，谢谢！ @Miss-you Github: xiaoxiaoling

**Comment by chacha923** [comment]
申请阅读 @Miss-you Github:chacha923

**Comment by 1314cc** [comment]
申请阅读 [@Miss-you](https://github.com/Miss-you) Github: 1314cc

**Comment by 1314cc** [comment]
申请阅读 @Miss-you  Github: 1314cc

**Comment by hamjl** [comment]
申请阅读 @Miss-you Github: hamjl

**Comment by bebc** [comment]
申请阅读 @Miss-you Github: bebc

**Comment by uncle-so-what** [comment]
申请阅读 @Miss-you Github: uncle-so-what

**Comment by lvchentao** [comment]
申请阅读 @Miss-you Github: lvchentao

**Comment by victorye81** [comment]
申请阅读 @Miss-you Github: victorye81

**Comment by longneicool** [comment]
申请阅读 @Miss-you Github: longneicool

**Comment by LamboChen** [comment]
申请阅读  @Miss-you  Github: LamboChen

**Comment by LamboChen** [comment]
申请阅读 @Miss-you  Github: LamboChen。  谢谢

**Comment by shewang-rh** [comment]
申请阅读 @Miss-you  Github: shewang-rh

**Comment by upengs** [comment]
申请阅读 @Miss-you Github: upengs

**Comment by cubixlin** [comment]
@Miss-you  申请阅读，感谢！ GitHub：cubixlin

**Comment by DrowringMan** [comment]
申请阅读

**Comment by DrowringMan** [comment]
申请阅读，感谢 @Miss-you , github :DrowingMan

**Comment by KinglyWayne** [comment]
申请阅读，谢谢！ @Miss-you Github: kinglywayne

**Comment by athlonxpgzw** [comment]
申请阅读，感谢 @Miss-you , github: athlonxpgzw

**Comment by qiankunli** [comment]
申请阅读，谢谢！ @Miss-you ,github: qiankunli

**Comment by lixianyang** [comment]
申请阅读，谢谢！ @Miss-you github: lixianyang

**Comment by dykhliww** [comment]
申请阅读！谢谢~ @Miss-you GitHub:dykhliww

**Comment by cnych** [comment]
申请阅读！谢谢~ @Miss-you GitHub:cnych

**Comment by skyshang1** [comment]
申请阅读！谢谢～ @Miss-you github: skyshang1

**Comment by Lionelpang** [comment]
申请阅读！谢谢～ @Miss-you github: Lionelpang

**Comment by Akuan1994** [comment]
申请阅读！谢谢～ @Miss-you github: akuan1994

**Comment by attlee-wang** [comment]
申请阅读！谢谢～ @Miss-you github: attlee-wang

**Comment by shenhonglei** [comment]
申请阅读 @Miss-you  github:shenhonglei

**Comment by bingws** [comment]
申请阅读 @Miss-you github:bingws

**Comment by xjxj1** [comment]
申请阅读@Miss-you  github:xjxj1

**Comment by Ghostbaby** [comment]
申请阅读 @Miss-you github:Ghostbaby

**Comment by yangguoandresolution** [comment]
申请阅读@Miss-you github:yangguoandresolution

**Comment by lovelife100** [comment]
申请阅读 @Miss-you Github:lovelife100

**Comment by menghuan** [comment]
申请阅读 @Miss-you Github:menghuan

**Comment by strictnerd** [comment]
申请阅读 @Miss-you Github:strictnerd

**Comment by fishingfly** [comment]
申请阅读，谢谢！ @Miss-you Github: fishingfly

**Comment by XinxingZh** [comment]
申请阅读 @Miss-you Github: XinxingZh

**Comment by awplxz** [comment]
申请阅读 @Miss-you Github：awplxz

**Comment by tgavriltg** [comment]
申请阅读 @Miss-you Github: tgavriltg

**Comment by qiuke123** [comment]
申请阅读 @Miss-you Github: qiuke123

**Comment by duhongyu** [comment]
申请阅读 @Miss-you Github: duhongyu

**Comment by dk-lockdown** [comment]
申请阅读 @Miss-you Github: dk-lockdown

**Comment by fighterhit** [comment]
申请阅读 @Miss-you Github: fighterhit

**Comment by baijunyao** [comment]
申请阅读 @Miss-you Github: baijunyao

**Comment by zuoshaoyi** [comment]
申请阅读 @Miss-you Github:  zuoshaoyi

**Comment by shangjunimo** [comment]
申请阅读 @Miss-you Github:shangjunimo

**Comment by Pilipupu** [comment]
申请阅读 @Miss-you Github: Pilipupu

**Comment by crazy-canux** [comment]
申请阅读  @Miss-you   Github: crazy-canux

**Comment by AndrewOYLK** [comment]
申请阅读 @Miss-you GitHub：AndrewOYLK

**Comment by lx1036** [comment]
申请阅读 @Miss-you Github: lx1036

**Comment by atuowgo** [comment]
申请阅读 @Miss-you Github: atuowgo

**Comment by JoeyX-u** [comment]
申请阅读 @Miss-you Github: JoeyX-u

**Comment by gnodli** [comment]
申请阅读 @Miss-you Github: gnodli

**Comment by nianjiang** [comment]
申请阅读 @Miss-you Github: nianjiang

**Comment by wanghaoran1988** [comment]
申请阅读 @Miss-you Github: wanghaoran1988

**Comment by zhiyuone** [comment]
申请阅读 @Miss-you Github: zhiyuone

**Comment by bryson-davis** [comment]
申请阅读，谢谢！ @Miss-you Github: bryson-davis

**Comment by yanghaichao12** [comment]
申请阅读 @Miss-you Github:yanghaichao12

**Comment by wxytjustb** [comment]
申请阅读  @Miss-you Github:wxytjustb

**Comment by OneCodeMonkey** [comment]
申请阅读 @Miss-you github:OneCodeMonkey

**Comment by bilc** [comment]
申请阅读 @Miss-you  github:bilc

**Comment by Michael754267513** [comment]
申请阅读 @Miss-you Github:Michael754267513

**Comment by Junnplus** [comment]
申请阅读 @Miss-you Github：Junnplus

**Comment by zhukaisjtu** [comment]
申请阅读 @Miss-you Github：zhukaisjtu

**Comment by lazybetrayer** [comment]
申请阅读 @Miss-you Github: lazybetrayer

**Comment by Pray3r** [comment]
申请阅读 @Miss-you Github: Pray3r

**Comment by david576111775** [comment]
申请阅读 @Miss-you Github: david576111775

**Comment by wood-push-melon** [comment]
申请阅读 @Miss-you Github:wood-push-melon

**Comment by yutian2011** [comment]
申请阅读  @Miss-you Github:yutian2011

**Comment by wangfong-ict** [comment]
申请阅读@ Miss-you GitHub：wangfong-ict

**Comment by GitHub-Bryce** [comment]
申请阅读@ Miss-you GitHub：Bryce

**Comment by Bryce-Wave** [comment]
申请阅读@ Miss-you GitHub：Bryce-Wave

**Comment by junfsir** [comment]
申请阅读@ Miss-you GitHub：junfsir

**Comment by w0nwig** [comment]
申请阅读@ Miss-you GitHub：w0nwig

**Comment by payall4u** [comment]
申请阅读  @Miss-you Github：payall4u

**Comment by yanghaichao12** [comment]
申请阅读 @Miss-you Github:yanghaichao12

**Comment by LinQing2017** [comment]
申请阅读 @Miss-you Github: LinQing2017

**Comment by evanlixin** [comment]
申请阅读 @Miss-you Github: evanlixin

**Comment by yaoliu** [comment]
申请阅读 @Miss-you Github: yaoliu

**Comment by liubingchuan** [comment]
申请阅读 @Miss-you Github: liubingchuan

**Comment by qyk1995** [comment]
qyk1995

**Comment by happen-zhang** [comment]
申请阅读 @Miss-you Github: happen-zhang

**Comment by liboyue23** [comment]
申请阅读 @Miss-you Github: liboyue23

**Comment by bluezd** [comment]
申请阅读 @Miss-you Github: bluezd

**Comment by te1203** [comment]
申请阅读,谢谢 @Miss-you Github: te1203

**Comment by cokkey** [comment]
申请阅读 @Miss-you Github:cokkey

**Comment by wenxuwan** [comment]
申请阅读 @Miss-you Github:wenxuwan

**Comment by geange** [comment]
申请阅读 @Miss-you github:geange

**Comment by McCoyZ** [comment]
申请阅读 @Miss-you  Github: McCoyZ

**Comment by chenyangxueHDU** [comment]
申请阅读 @Miss-you github:chenyangxueHDU

**Comment by appregidc** [comment]
申请阅读，谢谢 @Miss-you github:appregidc

**Comment by SongYintao** [comment]
申请阅读 @Miss-you github:SongYintao

**Comment by chrisho** [comment]
申请阅读 @Miss-you GitHub：chrisho

**Comment by just-do1** [comment]
申请阅读 @Miss-you github: just-do1

**Comment by hamjl** [comment]
申请阅读 @Miss-you github: hamjl

**Comment by qiushido** [comment]
申请阅读 @Miss-you Github: qiushido

**Comment by liupeng0518** [comment]
申请阅读 @Miss-you Github: liupeng0518

**Comment by W-YJ** [comment]
申请阅读 @Miss-you Github: W-YJ

**Comment by chaimeishan** [comment]
申请阅读 @Miss-you Github: chaimeishan

**Comment by JulieMei325** [comment]
申请阅读 @Miss-you Github: JulieMei325

**Comment by NataShare** [comment]
申请阅读 @Miss-you Github: natashare

**Comment by elfgzp** [comment]
申请阅读 @Miss-you Github: elfgzp

**Comment by HelloChenHZ** [comment]
申请阅读 @Miss-you Github: HelloChenHZ

**Comment by haoheipi** [comment]
申请阅读 @Miss-you Github: haoheipi

**Comment by wzzcanoe** [comment]
申请阅读 @Miss-you  github：django wang （wzzcanoe@163.com）

**Comment by renjie-zhang** [comment]
申请阅读 @Miss-you github： renjie-zhang

**Comment by gitsrc** [comment]
申请阅读，多谢 @Miss-you  GitHub：gitsrc

**Comment by xinghui-hou** [comment]
申请阅读 多谢 @Miss-you Github： Xinghui Hou

**Comment by WangTimo** [comment]
申请阅读，谢谢

**Comment by JC1O24** [comment]
申请阅读，多谢 @Miss-you GitHub：JC1O24

**Comment by Fordisk123** [comment]
申请阅读，谢谢！ @Miss-you Github: Fordisk123

**Comment by snuglove** [comment]
申请阅读 @Miss-you Github: snuglove

**Comment by zhaolibingit** [comment]
申请阅读 @Miss-you Github: zhaolibingit

**Comment by sober-wang** [comment]
申请阅读

**Comment by sober-wang** [comment]
申请阅读 @Miss-you Github: sober-wang

**Comment by GoGoCoding** [comment]
申请阅读 @Miss-you

**Comment by identifysun** [comment]
申请阅读，谢谢！ @Miss-you Github: identifysun

**Comment by partuoli** [comment]
申请阅读 @Miss-you Github: rawland

**Comment by partuoli** [comment]
申请阅读 @Miss-you Github: partuoli

**Comment by fangxingfu** [comment]
申请阅读 @Miss-you Github: fangxingfu

**Comment by andyrewOO** [comment]
申请阅读，感谢 @Miss-you Github: andyrewOO

**Comment by icersummer** [comment]
申请阅读 @Miss-you Github: icersummer

**Comment by headshot289** [comment]
申请阅读 @Miss-you  Github: headshot289

**Comment by hanyouqing** [comment]
申请阅读 @Miss-you Github: hanyouqing

**Comment by shitangdama** [comment]
申请阅读 @Miss-you Github: shitangdama

**Comment by ysicing** [comment]
申请阅读 @Miss-you  Github : @ysicing

**Comment by DeepLJH0001** [comment]
申请阅读 @Miss-you GitHub：DeepLJH0001

**Comment by liulixiang1988** [comment]
申请阅读 @Miss-you GitHub：@liulixiang1988

**Comment by zhangfane** [comment]
申请阅读 @Miss-you GitHub：zhangfane

**Comment by cloudonly** [comment]
申请阅读 @Miss-you GitHub：cloudonly

**Comment by oldthreefeng** [comment]
申请阅读 @Miss-you GitHub: oldthreefeng

**Comment by sayicui** [comment]
申请阅读 @Miss-you GitHub: sayicui

**Comment by AH-Toby** [comment]
申请阅读 @Miss-you GitHub: AH-Toby

**Comment by chou-o-ning** [comment]
申请阅读 @Miss-you GitHub: chou-o-ning

**Comment by MedicineZhong** [comment]
申请阅读 @Miss-you Github: MedicineZhong

**Comment by helios741** [comment]
申请阅读 @Miss-you  Github: helios741

**Comment by Zh1Cheung** [comment]
申请阅读 @Miss-you  Github: Zh1Cheung

**Comment by kadinzhu** [comment]
申请阅读 @Miss-you Github: @kadinzhu

**Comment by bingerambo** [comment]
申请阅读 @Miss-you GitHub：bingerambo

**Comment by rootsongjc** [comment]
通知：本书已被引入国内，翻译版即将出版发行，若您喜欢本书，请购买正版。

**Comment by chen-bin1314** [comment]
> 《Programming Kubernetes》本书即将引进国内出版，敬请关注。

申请阅读
