### ISSUE TITLE
[提问]client-go restclient 封装http 

### ISSUE THREAD

**Issue by liuyangc3** [cloudnativeto/sig-k8s-source-code#17]
```go
func (r *Request) Do(ctx context.Context) Result {
	var result Result
	err := r.request(ctx, func(req *http.Request, resp *http.Response) {
		result = r.transformResponse(resp, req)
	})
	if err != nil {
		return Result{err: err}
	}
	return result
}


func (r *Request) request(ctx context.Context, fn func(*http.Request, *http.Response)) error {
...
    resp, err := client.Do(req)
...
    fn(req, resp)
    return true
}
```

问题: 为什么Do要用传入 fn 的形式 去转换 Response, 直接按照下面的写不行么, 例如
```go
func (r *Request) Do(ctx context.Context) Result {
	result, err := r.request(ctx)
        if err != nil {
		return Result{err: err}
	}
	return result
}

func (r *Request) request(ctx context.Context, fn func(*http.Request, *http.Response)) (Result, error) {
...
    resp, err := client.Do(req)
...
   result = r.transformResponse(resp, req)
   return result, nil
}
```

**Comment by lianghao208** [comment]
我个人认为这样写可以将request方法和fn解耦，比如这里的Do方法中的fn为transformResponse，是clientSet将apiserver返回的资源对象反序列化成kubernetes的资源对象数据结构的方法实现，而下面的DoRaw方法的transformUnstructuredResponseError又是另一种fn的实现，我们可以还可以自己实现fn对clientSet进行封装，这样可重用性会更好。

**Comment by helight** [comment]
上面一种写法确实可以根据请求不同而设置不同的处理函数。

下面这种方式就比较固定了。

**Comment by Howie66** [comment]
上面的可复用性更强吧

**Comment by gasxia** [comment]
> request 函数有一个函数类型的参数，该参数是用来解析 response。  
> 
> 这个设计是很巧妙的，解析 response 的需求是不一样的，需要调用者去实现。那为什么不返回 resp.Body 给调用者处理呢？因为 request 函数有责任关闭 resp.Body 字节流，另一个我觉得的原因是支持解析 response 的函数发现需要重试的时候，能复用 request 函数的重试机制（client-go 并没有这样做）。

关于client-go中的request函数，我总结了一篇文章《学习 client-go 中 request 函数的实现》。上面的引用是文章的第一小节。

**Comment by zhaoweiguo** [comment]
> 学习 client-go 中 request 函数的实现

文章加上链接吧
