### ISSUE TITLE
创建一个调查问卷

### ISSUE THREAD

**Issue by rootsongjc** [cloudnativeto/sig-k8s-source-code#2]
创建一个调查问卷，旨在了解研习会中成员对 Go 语言、Kubernetes 的了解程度。每个人的基础、可用时间都不一样，不可能保证所有人进度都一致，该问卷可以帮助研习会管理员控制研习进度。

## 问卷细节

- 使用腾讯问卷
- 在研习会微信群中发放，仅限研习会成员填写
- 问卷内容待定

**Comment by ezliuja** [comment]
问卷内容：
1. 最想在学习的K8S模块是？
2. 你的K8S熟悉程度是： a: 有基本了解以及使用  b: 有看过部分源码，但遇到很大问题。
3. 你对go语言的掌握程度： a: 只闻其名，未上手，属小白一枚  b:  看过基本语法， c: 有业务开发经验
4. 你最希望每一个小任务的完成时间： a: 1小时一下  b: 1-3小时  c: 半天

**Comment by Lvzhenqian** [comment]
1. scheduler apiserver

**Comment by Lvzhenqian** [comment]
1. scheduler apiserver 
2. b
3. c
4. b

**Comment by Jeremy-boo** [comment]
> 问卷内容：
> 
> 1. 最想在学习的K8S模块是？
> 2. 你的K8S熟悉程度是： a: 有基本了解以及使用  b: 有看过部分源码，但遇到很大问题。
> 3. 你对go语言的掌握程度： a: 只闻其名，未上手，属小白一枚  b:  看过基本语法， c: 有业务开发经验
> 4. 你最希望每一个小任务的完成时间： a: 1小时一下  b: 1-3小时  c: 半天

1. controller模块和api server 相关部分
2.  有基本的了解，做过一些基于k8s的二次开发
3. c
4 .a

**Comment by rootsongjc** [comment]
调查问卷已创建并收集完成。
![image](https://user-images.githubusercontent.com/3328185/89150384-03443f80-d591-11ea-9b7a-0581e925518e.png)

**Comment by SnowerWkh** [comment]
1、kcm
2、a
3、c
4、b
