### ISSUE TITLE
[提问]CachedDiscoveryClient是如何创建出来的？

### ISSUE THREAD

**Issue by herbguo** [cloudnativeto/sig-k8s-source-code#23]
今天看DiscoveryClient客户端的缓存，api-server请求/api和/apis接口时调用ServerGroupsAndResources继而调用 ServerGroups

如果有缓存，是先查缓存的，代码里DiscoveryInterface这个接口进行ServerGroups的调用，具体是调用discovery_client.go中的ServerGroups方法，还是调用cached_discovery.go中的ServerGroups方法，则取决于创建的Client的类型是DiscoveryClient还是CachedDiscoveryClient，

但是在查看创建Client这块的源码时，久久不能找到哪里创建的CachedDiscoveryClient，所以来这里问一下，看看能不能得到答案，谢谢！

**Comment by Luffy110** [comment]
[NewCachedDiscoveryClientForConfig](https://github.com/kubernetes/client-go/blob/release-1.18/discovery/cached/disk/cached_discovery.go#L273) 这里算是吗？

**Comment by herbguo** [comment]
> [NewCachedDiscoveryClientForConfig](https://github.com/kubernetes/client-go/blob/release-1.18/discovery/cached/disk/cached_discovery.go#L273) 这里算是吗？

额，这个在disk包下，难怪我从clientcmd包下找不到入口，多谢！

**Comment by yangguoandresolution** [comment]
这是kubectl命令行本地缓存， kubectl apply这个 kubetl: main.go->cmd.go:NewDefaultKubectlCommand->cmd.go:NewDefaultKubectlCommandWithArgs->cmd/apply/apply.go:NewCmdApply->apply.go:ToDiscoveryClient->cli-runtime/pkg/genericclioptions/config_flags.go:237->client-go/discovery/cached/disk/cached_discovery.go:NewCachedDiscoveryClientForConfig

**Comment by herbguo** [comment]
> 这是kubectl命令行本地缓存， kubectl apply这个 kubetl: main.go->cmd.go:NewDefaultKubectlCommand->cmd.go:NewDefaultKubectlCommandWithArgs->cmd/apply/apply.go:NewCmdApply->apply.go:ToDiscoveryClient->cli-runtime/pkg/genericclioptions/config_flags.go:237->client-go/discovery/cached/disk/cached_discovery.go:NewCachedDiscoveryClientForConfig

好的，多谢！
