### ISSUE TITLE
使用容器环境构建k8s：提前导入需要的镜像，make quick-release的时候还是要去拉镜像

### ISSUE THREAD

**Issue by QQ-ing** [cloudnativeto/sig-k8s-source-code#6]
环境：centos 7    k8s:1.14   go:1.12

提前导入镜像：
[root@localhost ~]# docker images
REPOSITORY        TAG        IMAGE ID        CREATED        SIZE
kube-build        build-fbd5cbc23f-5-v1.12.12-1      6933b19a02f5      12 minutes ago     2.52GB
k8s.gcr.io/kube-cross      v1.12.12-1          adda3dc86c33        9 months ago        1.87GB
k8s.gcr.io/debian-iptables-amd64      v11.0.2      01a746008995      16 months ago       45.4MB
k8s.gcr.io/debian-base-amd64      v1.0.0      204e96332c91      16 months ago      42.3MB
![image](https://user-images.githubusercontent.com/9510705/88754289-e07cea00-d190-11ea-8de1-855699904077.png)

执行make quick-release :
[root@localhost kubernetes]# make quick-release
+++ [0728 23:10:02] Verifying Prerequisites....
+++ [0728 23:10:02] Building Docker image kube-build:build-fbd5cbc23f-5-v1.12.12-1
+++ [0728 23:10:46] Creating data container kube-build-data-fbd5cbc23f-5-v1.12.12-1
+++ [0728 23:11:10] Syncing sources to container
+++ [0728 23:11:28] Running build command...
+++ [0728 23:11:36] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/deepcopy-gen
+++ [0728 23:11:44] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/defaulter-gen
+++ [0728 23:11:50] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/conversion-gen
+++ [0728 23:11:59] Building go targets for linux/amd64:
    ./vendor/k8s.io/kube-openapi/cmd/openapi-gen
+++ [0728 23:12:08] Building go targets for linux/amd64:
    ./vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [0728 23:12:10] Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/cloud-controller-manager
    cmd/kubelet
    cmd/kubeadm
    cmd/hyperkube
    cmd/kube-scheduler
    vendor/k8s.io/apiextensions-apiserver
    cluster/gce/gci/mounter
+++ [0728 23:16:20] Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kubeadm
    cmd/kubelet
+++ [0728 23:16:48] Building go targets for linux/amd64:
    cmd/kubectl
+++ [0728 23:17:03] Building go targets for linux/amd64:
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/genyaml
    cmd/genswaggertypedocs
    cmd/linkcheck
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
+++ [0728 23:19:34] Building go targets for linux/amd64:
    cmd/kubemark
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e_node/e2e_node.test
+++ [0728 23:20:33] Syncing out of container
+++ [0728 23:20:44] Building tarball: src
+++ [0728 23:20:44] Building tarball: manifests
+++ [0728 23:20:44] Starting tarball: client linux-amd64
+++ [0728 23:20:44] Waiting on tarballs
+++ [0728 23:20:53] Building images: linux-amd64
+++ [0728 23:20:53] Building tarball: node linux-amd64
+++ [0728 23:21:01] Starting docker build for image: cloud-controller-manager-amd64
+++ [0728 23:21:01] Starting docker build for image: kube-apiserver-amd64
+++ [0728 23:21:01] Starting docker build for image: kube-controller-manager-amd64
+++ [0728 23:21:01] Starting docker build for image: kube-scheduler-amd64
+++ [0728 23:21:01] Starting docker build for image: kube-proxy-amd64
+++ [0728 23:21:01] Building hyperkube image for arch: amd64
+++ [0728 23:21:01] Building conformance image for arch: amd64
Sending build context to Docker daemon  36.64MB
Step 1/2 : FROM k8s.gcr.io/debian-iptables-amd64:v11.0.2
Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
!!! [0728 23:21:24] Call tree:
!!! [0728 23:21:24]  1: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:231 kube::release::create_docker_images_for_server(...)
!!! [0728 23:21:24]  2: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:237 kube::release::build_server_images(...)
!!! [0728 23:21:24]  3: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:93 kube::release::package_server_tarballs(...)
!!! [0728 23:21:24]  4: build/release.sh:45 kube::release::package_tarballs(...)
Sending build context to Docker daemon   39.2MB
Step 1/2 : FROM k8s.gcr.io/debian-base-amd64:v1.0.0
Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
!!! [0728 23:21:34] Call tree:
!!! [0728 23:21:34]  1: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:231 kube::release::create_docker_images_for_server(...)
!!! [0728 23:21:34]  2: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:237 kube::release::build_server_images(...)
!!! [0728 23:21:34]  3: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:93 kube::release::package_server_tarballs(...)
!!! [0728 23:21:34]  4: build/release.sh:45 kube::release::package_tarballs(...)
Sending build context to Docker daemon    115MB
Step 1/2 : FROM k8s.gcr.io/debian-base-amd64:v1.0.0
Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
!!! [0728 23:21:40] Call tree:
!!! [0728 23:21:40]  1: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:231 kube::release::create_docker_images_for_server(...)
!!! [0728 23:21:40]  2: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:237 kube::release::build_server_images(...)
!!! [0728 23:21:40]  3: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:93 kube::release::package_server_tarballs(...)
!!! [0728 23:21:40]  4: build/release.sh:45 kube::release::package_tarballs(...)
Sending build context to Docker daemon    167MB
Step 1/2 : FROM k8s.gcr.io/debian-base-amd64:v1.0.0
Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
!!! [0728 23:21:50] Call tree:
!!! [0728 23:21:50]  1: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:231 kube::release::create_docker_images_for_server(...)
!!! [0728 23:21:50]  2: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:237 kube::release::build_server_images(...)
!!! [0728 23:21:50]  3: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:93 kube::release::package_server_tarballs(...)
!!! [0728 23:21:50]  4: build/release.sh:45 kube::release::package_tarballs(...)
Sending build context to Docker daemon  99.91MB
Step 1/2 : FROM k8s.gcr.io/debian-base-amd64:v1.0.0
Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
!!! [0728 23:22:00] Call tree:
!!! [0728 23:22:00]  1: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:231 kube::release::create_docker_images_for_server(...)
!!! [0728 23:22:00]  2: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:237 kube::release::build_server_images(...)
!!! [0728 23:22:00]  3: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:93 kube::release::package_server_tarballs(...)
!!! [0728 23:22:00]  4: build/release.sh:45 kube::release::package_tarballs(...)
Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
make[1]: *** [build] Error 1
!!! [0728 23:22:00] Call tree:
!!! [0728 23:22:00]  1: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:420 kube::release::build_hyperkube_image(...)
!!! [0728 23:22:00]  2: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:231 kube::release::create_docker_images_for_server(...)
!!! [0728 23:22:00]  3: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:237 kube::release::build_server_images(...)
!!! [0728 23:22:00]  4: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:93 kube::release::package_server_tarballs(...)
!!! [0728 23:22:00]  5: build/release.sh:45 kube::release::package_tarballs(...)
Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
make[1]: *** [build] Error 1
!!! [0728 23:22:10] Call tree:
!!! [0728 23:22:10]  1: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:424 kube::release::build_conformance_image(...)
!!! [0728 23:22:10]  2: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:231 kube::release::create_docker_images_for_server(...)
!!! [0728 23:22:10]  3: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:237 kube::release::build_server_images(...)
!!! [0728 23:22:10]  4: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:93 kube::release::package_server_tarballs(...)
!!! [0728 23:22:10]  5: build/release.sh:45 kube::release::package_tarballs(...)
!!! [0728 23:22:10] previous Docker build failed
!!! [0728 23:22:10] Call tree:
!!! [0728 23:22:10]  1: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:231 kube::release::create_docker_images_for_server(...)
!!! [0728 23:22:10]  2: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:237 kube::release::build_server_images(...)
!!! [0728 23:22:10]  3: /root/go/src/k8s.io/kubernetes/build/lib/release.sh:93 kube::release::package_server_tarballs(...)
!!! [0728 23:22:10]  4: build/release.sh:45 kube::release::package_tarballs(...)
!!! [0728 23:22:10] previous tarball phase failed
make: *** [quick-release] Error 1
[root@localhost kubernetes]# 

期望结果：期望make quick-release 成功执行完成。

**Comment by chenpfeisoo** [comment]
你可以提前将一些需要的镜像 下载下来

**Comment by QQ-ing** [comment]
我已经提前将需要的镜像下载下来也导入了，但是还是不行。我换docker-desktop部署了k8s环境了，编译的时候也是直接使用make all来编译的。
