### ISSUE TITLE
[募集] 为Kubernetes 源码研习社募集三位 maintainer

### ISSUE THREAD

**Issue by rootsongjc** [cloudnativeto/sig-k8s-source-code#9]
2020年08月04日晚，Kubernetes 源码研习社第一期 kickoff 完成，确定了活动基于本仓库来提问、整理和归档问题，通过[云原生社区官网](https://cloudnative.to)、公众号和知识星球来分享讨论成功和经验的基本流程。

为了更好的组织本次活动，需要三位活动参加者作为本仓库的maintainer。

## Maintainer 的权利

1. 拥有本仓库的 maintainer 权限（push、管理 issue）
1. 名誉学习委员，展示在本仓库 README 首页
1. 召集学员对某个话题的讨论
1. 分享将优先发表在云原生社区的官网、公众号及其他渠道

## Maintainer 的义务

1. 对一期学员在本仓库的 issue 进行格式化，包括 issue 标题的格式化、内容的模板的制定、内容的格式化、设置 label、做好分类、及时的关闭和处理 issue
1. 对微信群中讨论的有价值的问题创建 issue 并持续跟踪
1. 其他有助于成员之间交流和学习的事情

## 时限

- Maintainer 可以长期担任
- 每次新的一期 Kubernetes 源码研习社可以产生新的 Maintainer

## 成为 Maintainer 的条件

1. Maintainer 从参加Kubernetes 源码剖析的一期学员中产生
1. Maintainer 必须保证有充足的时间参与本次活动
1. Maintainer 需要多 Kubernetes 及一期活动讨论的话题有一定认识
1. Maintainer 通过自荐和一期研习会会长 @Miss-you 及 @rootsongjc 确认产生

请大家自告奋勇自荐成为一期的学习委员。

**Comment by wenhuwang** [comment]
报名  虽然没有当过maintainer，但是希望通过学习成为一名合格的maintainer

**Comment by zouyuxuan** [comment]
我想成为一名Maintainer，我怕自己在k8s知识储备不够，不过我想挑战一下自己。

**Comment by gyohuangxin** [comment]
我想报名成为研习社的maintainer，我目前在IBM从事Openshift私有云相关的开发工作，对K8S有一定的了解和认识。希望和大家一起交流成长～

**Comment by rootsongjc** [comment]
我再列举几个 maintainer 接下来需要做的事情：
1. 设置 GitHub Issue 模板，这个是为了划分类型，如源码阅读经验分享、提问等
1. 修改 README，整理一期活动的介绍、参与方式等
1. 整理已有的 issue，将 title 格式化（需要确定一个 title 的模板）

**Comment by YouEclipse** [comment]
报名。日常使用github，自己也有维护一些个人的小项目。希望能和大家一起学习成长。

**Comment by cobb-tx** [comment]
报名。之前在一家小公司做了devops，最近待业在家系统的学习一下k8s，时间有多希望能和大家一起学习成长。

**Comment by rootsongjc** [comment]
Maintainer 人选将在本周四（8 月 6 日）确定。

**Comment by gasxia** [comment]
报名。之前就参与了这次活动的策划，阅读过《Programming Kubernetes》,在工作中也有一些场景需要参考Kubernetes源码。  

我愿意在工作之余参与到社区的活动中，与大家一起学习。

**Comment by welcome112s** [comment]
报名。在公司一直从事go 服务相关的开发，也使用了k8s ，对源码比较感兴趣，希望一起成长。

**Comment by rootsongjc** [comment]
> 我想报名成为研习社的maintainer，我目前在IBM从事Openshift私有云相关的开发工作，对K8S有一定的了解和认识。希望和大家一起交流成长～
> 
> ps：抱歉，我没有进群可以拉一下我吗～ h13482547409

已申请微信好友。

**Comment by rootsongjc** [comment]
> 报名。在公司一直从事go 服务相关的开发，也使用了k8s ，对源码比较感兴趣，希望一起成长。

你还没在[表格](https://docs.qq.com/sheet/DR3l5U3lLdE9BYktY?tab=caenkx)中登记吧，怎么联系你呢？

**Comment by rootsongjc** [comment]
关于 maintainer 的选择会在周五晚上 9 点进行一次 zoom 会议确认。 会议地址：https://us02web.zoom.us/j/81380785627

**Comment by rootsongjc** [comment]
2020年08月07日晚上 9 点根据zoom 会议讨论：
@gyohuangxin 在 IBM 参与 OpenShift 开发工作，日常开发中就使用 GitHub，有丰富的经验，时间比较灵活，随时可以参与社区讨论。
@cobb-tx 在做 Kubernetes 开发。
@YouEclipse 在做 Kubernetes、Istio 微服务落地工作，在外企中使用 GitHub 比较多，有维护个人项目，对 Kubernetes 比较感兴趣，日常时间比较多参与社区。
@JaneLiuL 有团队管理经验，时间比较充裕，在群内关注比较多。
@zhaoweiguo  参与过开源项目，熟悉 issue 管理，时间充裕。
@zouyuxuan Golang 开发，接触 Kubernetes 有一年，近一个月可以参与社区。
@gasxia 做云原生开发，使用 Rancher 做 PaaS 开发，GitHub 和社区活跃，参与过 TalkGo，在社区投过稿。
@wenhuwang 容器落地和开发，经常使用 GitHub，熟悉流程，日常时间有保证。

根据已参与社区时间和投入，一期确认三位 maintainer @gasxia @wenhuwang @zhaoweiguo

**Comment by rootsongjc** [comment]
Maintainer 的任务：
1. @rootsongjc 创建一个腾讯文档，用于编辑源码研习会参与规范，给三位 Maintainer 全新啊
2. 邀请三位 maintainer 加入 GitHub team，并给与 maitainer 权限

下周一出具一个活动规范。
